---

- hosts: telegram_bot_ec2
  remote_user: ubuntu
  become: true
  become_method: sudo
  gather_facts: false
  vars:
    app_dir: /app
  tasks:
    - name:  Update apt cache
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        name: ['supervisor', 'python3.7', 'python-pip', 'git']

    - name: Install "pipenv"
      pip:
        name: pipenv

    - name: Copy application to remote server
      synchronize:
        src: ../app
        dest: /
#        rsync_opts:
#          - "--exclude=db.sqlite"

    - name: Copy supervisor config
      copy:
        src: supervisord.conf
        dest: /etc/supervisor/conf.d/app.conf

    - name: Setup pipenv
      command: pipenv install
      args:
          chdir: "{{app_dir}}"

# TODO: enable service?\
# sudo systemctl enable supervisor

    - name: Start supervisor
      service:
        name: supervisor
        state: started

    - name: Run supervisor
      supervisorctl:
       name: 'bot_app'
       state: present
       config: /etc/supervisor/supervisord.conf

