---

- hosts: telegram_bot_ec2
  remote_user: ubuntu
  become: true
  become_method: sudo
  gather_facts: false
  tasks:
#    - name:  Update apt cache
#      apt:
#        update_cache: yes

    - name: Install packages
      apt:
        name: ['supervisor', 'python-pip', 'git']

    - name: Install "pipenv"
      pip:
        name: pipenv

    - name: Clone project from github
      git:
        repo: 'https://github.com/ar0ne/telegram_bot_playground.git'
        dest: /tmp/bot_app

    - name: Get status of app folder
      stat: path=/app
      register: app_stat

    - name: Move project to app folder
      command: mv /temp/bot_app/app /app
      when: app_stat.stat.exists
